import os, modulo.mimodulo

os.system('cls')

print('Resto: ', modulo.mimodulo.obtener_resto(4,2))

# PONER EL PADRE DE LA CARPETA MODULO
# SET PYTHONPATH=O:\TRABAJANDO\PROJECTS___PYTHON\PYTHON_0023\2;%PYTHONPATH%
# COMO LLEGAMOS SOLO HASTA LA CARPETA "2" Y MIMODULO.PY SE ENCUENTRA EN LA CARPETA "MODULO"
# ENTONCES AGREGAMOS "MODULO.MIMODULO"